import { Link } from "react-router-dom";
import {
  ArrowRight,
  Camera,
  CheckCircle2,
  FileCheck2,
  SearchCheck,
  ShieldCheck,
} from "lucide-react";

function About() {
  return (
    <main>
      {/* HERO */}
      <section className="bg-[#0b1220] text-white">
        <div className="gc-container py-14 sm:py-16 md:py-24">

          <div className="grid lg:grid-cols-2 gap-9 sm:gap-12 lg:gap-14 items-center">

            <div>
              <div className="gc-eyebrow">
                About GaariCheck
              </div>

              <h1 className="text-3xl sm:text-4xl md:text-6xl font-black leading-tight mt-4">
                Making vehicle inspection
                <span className="text-orange-500 block">
                  easier to access.
                </span>
              </h1>

              <p className="text-slate-300 text-base sm:text-lg leading-7 sm:leading-8 mt-5 sm:mt-6 max-w-xl">
                GaariCheck is a remote vehicle inspection
                service designed to help customers understand
                visible vehicle condition through structured
                photos, videos and professional human review.
              </p>

              <Link
                to="/pricing"
                className="gc-btn-primary w-full sm:w-auto mt-7 sm:mt-8 gap-2"
              >
                Start an Inspection
                <ArrowRight size={18} />
              </Link>
            </div>

            <div className="relative">
              <img
                src="https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1400&q=85"
                alt="Vehicle inspection"
                className="rounded-[22px] sm:rounded-[28px] w-full h-[290px] sm:h-[360px] md:h-[420px] object-cover"
              />

              <div className="absolute -bottom-6 -left-6 bg-white text-[#0b1220] rounded-2xl shadow-xl p-5 hidden md:block">
                <div className="flex items-center gap-3">
                  <ShieldCheck className="text-green-600" />

                  <div>
                    <div className="font-black">
                      Human Reviewed
                    </div>

                    <div className="text-xs text-gray-500">
                      Remote visual assessment
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* PURPOSE */}
      <section className="gc-section bg-white">
        <div className="gc-container">

          <div className="grid lg:grid-cols-2 gap-8 sm:gap-10 lg:gap-14">

            <div>
              <div className="gc-eyebrow">
                Our Purpose
              </div>

              <h2 className="gc-title mt-3">
                Reduce uncertainty before making a vehicle decision.
              </h2>
            </div>

            <div>
              <p className="gc-description">
                Vehicle buyers often need more information
                before travelling to see a car or moving
                forward with a purchase. GaariCheck provides
                a structured way to collect vehicle evidence
                remotely and organize the findings into a
                clear digital report.
              </p>

              <p className="gc-description mt-5">
                Our current service focuses on visible
                condition based on submitted photos, videos
                and vehicle information. The assessment is
                reviewed by the GaariCheck team rather than
                automatically generated by AI.
              </p>
            </div>

          </div>
        </div>
      </section>

      {/* PRINCIPLES */}
      <section className="gc-section bg-[#f5f7fa]">
        <div className="gc-container">

          <div className="max-w-2xl">
            <div className="gc-eyebrow">
              How We Work
            </div>

            <h2 className="gc-title mt-3">
              A clear and structured inspection process.
            </h2>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-5 mt-8 sm:mt-12">

            <ValueCard
              icon={<Camera />}
              title="Structured Capture"
              text="Customers are guided through the vehicle photos and videos required for review."
            />

            <ValueCard
              icon={<SearchCheck />}
              title="Careful Review"
              text="Submitted vehicle evidence is reviewed by the GaariCheck inspection team."
            />

            <ValueCard
              icon={<FileCheck2 />}
              title="Clear Reporting"
              text="Important observations are organized into a digital inspection report."
            />

            <ValueCard
              icon={<ShieldCheck />}
              title="Customer Control"
              text="Inspection progress and completed reports remain accessible through the customer dashboard."
            />

          </div>

        </div>
      </section>

      {/* WHAT IT IS */}
      <section className="gc-section bg-white">
        <div className="gc-container">

          <div className="grid lg:grid-cols-2 gap-9 sm:gap-12 lg:gap-14 items-center">

            <div className="bg-[#0b1220] rounded-[22px] sm:rounded-[28px] p-5 sm:p-7 md:p-10 text-white">

              <h3 className="text-3xl font-black">
                What GaariCheck provides
              </h3>

              <div className="space-y-5 mt-8">

                {[
                  "Remote visual vehicle inspection",
                  "Guided vehicle photo and video submission",
                  "Human review of submitted evidence",
                  "Digital inspection status tracking",
                  "Downloadable PDF inspection report",
                ].map((item) => (
                  <div
                    key={item}
                    className="flex items-start gap-3"
                  >
                    <CheckCircle2
                      size={20}
                      className="text-green-400 mt-0.5 shrink-0"
                    />

                    <span className="text-slate-300">
                      {item}
                    </span>
                  </div>
                ))}

              </div>
            </div>

            <div>
              <div className="gc-eyebrow">
                Important to Know
              </div>

              <h2 className="gc-title mt-3">
                Remote visual inspection, not a physical workshop inspection.
              </h2>

              <p className="gc-description mt-5">
                GaariCheck's current service is based on
                customer-submitted media and information.
                Observations are therefore limited to what
                can reasonably be assessed from the provided
                visual evidence.
              </p>

              <p className="gc-description mt-5">
                This distinction will also be clearly stated
                in our final inspection reports and service
                terms.
              </p>
            </div>

          </div>

        </div>
      </section>

      {/* CTA */}
      <section className="px-4 pb-20 bg-white">
        <div className="gc-container">

          <div className="bg-[#0b1220] rounded-[22px] sm:rounded-[28px] px-5 sm:px-7 py-9 sm:py-12 md:px-12 flex flex-col lg:flex-row justify-between lg:items-center gap-7">

            <div>
              <h2 className="text-white font-black text-3xl">
                Ready to check a vehicle?
              </h2>

              <p className="text-slate-400 mt-2">
                Compare inspection packages and choose
                the level of review you need.
              </p>
            </div>

            <Link
              to="/pricing"
              className="gc-btn-primary w-full sm:w-auto gap-2"
            >
              View Packages
              <ArrowRight size={18} />
            </Link>

          </div>

        </div>
      </section>
    </main>
  );
}


function ValueCard({ icon, title, text }) {
  return (
    <div className="gc-card p-5 sm:p-6">
      <div className="w-12 h-12 rounded-xl bg-orange-100 text-orange-600 flex items-center justify-center">
        {icon}
      </div>

      <h3 className="font-black text-xl text-[#0b1220] mt-5">
        {title}
      </h3>

      <p className="text-sm text-gray-500 leading-7 mt-3">
        {text}
      </p>
    </div>
  );
}

export default About;